#!/bin/bash


GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
GIT_TAG=$(git rev-parse --short --verify HEAD)
TAG=${GIT_BRANCH}-${GIT_TAG}


DEPS_IMAGE="galleri/webapp-deps"
WEBAPP_IMAGE="galleri/webapp"

set_latest_tag() {
    docker tag $1:${TAG} $1:latest
}


docker_hub_build() {
    echo "building deps..."
    docker build \
           -t ${DEPS_IMAGE}:${TAG} \
           -f ./Dockerfile.deps \
           . \
        && set_latest_tag ${DEPS_IMAGE} \
        && echo "building webapp..." \
        && docker build \
                  -t ${WEBAPP_IMAGE}:${TAG} \
                  . \
        && set_latest_tag ${WEBAPP_IMAGE}
}

local_build() {
    echo "building webapp..."
    docker build -t ${WEBAPP_IMAGE}:latest .
}


if [[ "${IS_DOCKER_HUB}" -eq "1" ]]; then
    docker_hub_build
else
    local_build
fi
