#!/bin/bash

docker run --rm \
       --net=host \
       -e TARGET_URL=${BUILD_HOOK_ENDPOINT}/build-success/galleri_webapp \
       -e HOOK_KEY=${HOOK_KEY} \
       tengelisconsulting/docker-hub-hooks
